### ISSUE TITLE
Adding bindgen to build-dependencies prevents crate from being no_std

### ISSUE THREAD

**Issue by aleksanb** [rust-lang/rust-bindgen#1439]
This doesn't really seem intentional, although this might be more of a cargo issue than a bindgen issue.

Minimal example that doesn't work when you add bindgen to build-rependencies:
main.rs:
```rust
#![feature(lang_items, start)]
#![no_std]

use core::panic::PanicInfo;
use libc;

#[panic_handler]
fn panic(_panic: &PanicInfo<'_>) -> ! { 
    loop {}
}

#[lang = "eh_personality"]
extern "C" fn eh_personality() {}

#[start]
fn start(_argc: isize, _argv: *const *const u8) -> isize {
    0   
}
```

Cargo.toml:
```toml
[package]
name = "yolo"
version = "0.1.0"
authors = ["aleksanb"]
edition = "2018"

[dependencies]
libc = {version = "0.2.*", default-features = false}

[build-dependencies]
bindgen = "*"
```

I used to invoke bindgen via the shell, which would work fine with my no_std crate, but using it in a build.rs prevents me from using no_std at all.
