### ISSUE TITLE
libclang not found when building using azure pipelines for windows

### ISSUE THREAD

**Issue by mamcx** [rust-lang/rust-bindgen#2091]
Recently all my windows build failed with:

> thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', D:\a\1\s\$(HOME)/.cargo/registry\src\github.com-1ecc6299db9ec823\bindgen-0.58.1\src/lib.rs:2057:31

I have this small sample:

```toml
[package]
name = "sync"
version = "0.2.0"
authors = ["Mario Alejandro Montoya <mamcx@elmalabarista.com>"]
edition = "2018"

[dependencies]
xlsxwriter = "0.3.5"
```

I tried to set the ENV but it not work:

```yaml
trigger:
  branches:
    include:
      - 'master'

strategy:
  maxParallel: 2
  matrix:
    windows-stable:
      imageName: 'windows-latest'
      rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - script: |
      cargo version
      rustc --version
      rustup toolchain list
      setx PATH "C:\Program Files\LLVM\bin;%PATH%" /M
      setx LIBCLANG_PATH "C:\Program Files\LLVM\bin" /M
      echo %path:;=&echo.%
      refreshenv
    displayName: Versions

  - script: |
      cargo build --bin sync --release
    env:
      LIBCLANG_PATH: "C:\Program Files\LLVM\bin"
    displayName: Cargo build Windows
    condition:  eq( variables['Agent.OS'], 'Windows_NT' )
```

P.D. This could be similar to https://github.com/rust-lang/rust-bindgen/issues/1797.
