### ISSUE TITLE
using the github repo version of `bindgen` points to a very old version.

### ISSUE THREAD

**Issue by pvdrz** [rust-lang/rust-bindgen#2459]
It is a common pattern to use the `git` repo of a dependency to try new features that have not been released yet. So it would be normal for users to add the following in their cargo manifest:
```toml
[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen" }
```
However that would actually fetch the `HEAD` branch whose last commit is from 2019. Users would have to add the following then:

```toml
[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", branch = "main" }
```

Or even `branch = "master"`. I wonder if there's a reason why this `HEAD` branch exist and if we should document how to use "the latest" bindgen somewhere.

cc @emilio @amanjeev @kulp
