### ISSUE TITLE
Update clang-sys

### ISSUE THREAD

**Issue by theoparis** [rust-lang/rust-bindgen#2844]
Please update clang-sys to 1.8.1 in bindgen, previous versions do not handle static linking or libc++ properly.

Additionally I can't update clang-sys myself:

```
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.49.3 (https://github.com/rust-lang/rust-bindgen#ad0bf8e6)`
    ... which satisfies git dependency `bindgen` of package `nixc v0.0.1 (/home/theo/Documents/nixc)`
versions that meet the requirements `^0.28.0` are: 0.28.1, 0.28.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v1.8.2 (https://github.com/KyleMayes/clang-sys#e4c9b7ef)`
    ... which satisfies git dependency `clang-sys` of package `nixc v0.0.1 (/home/theo/Documents/nixc)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "clang"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `clang-sys` which could resolve this conflict
```

Cargo.toml:
```toml
[package]
name = "nixc"
version = "0.0.1"
edition = "2021"

[dependencies]
rnix = "0.11.0"
clap = "4.5.4"

[workspace]
members = []
resolver = "2"

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", features = ["static"], default-features = false }
clang-sys = { git = "https://github.com/KyleMayes/clang-sys", version = "1", default-features = false, features = ["libcpp", "static"] }

[patch.crates-io]
clang-sys = { git = "https://github.com/KyleMayes/clang-sys", version = "1" }


```
